/**
 * MicroUnits - Pauses Analysis of XML files generated by Translog II software.
 * For Translog II details See <http://bridge.cbs.dk/platform/?q=Translog-II>
 *
 * Copyright (C) 2014 Gabriel Ed. da Silva
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package Modelo;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.StringReader;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;

/**
 *
 * @author Gabriel Ed
 */
public class AnotherParse {

    //Expressões
    /**
     * Expressão para recuperar os valores de Key
     */
    public static final String expressionKey = "//Key";

    /**
     * Expressão para recuperar os valores de Fix
     */
    public static final String expressionFix = "//Fix";

    /**
     * Expressão utilizada para recuperar o tempo final.
     */
    public static final String expressionTempoFinal = "//System[@Value='STOP']";

    /**
     * Faz o parse de um documento XML gerado pelo Translog II. Gerando um objeto
     * a ser manipulado.
     * @param filename - Caminho para um Arquivo
     * @return Objeto MyDoc referente ao arquivo processado.
     * @throws FileNotFoundException
     * @throws IOException
     * @throws Exception
     */
    public static MyDoc parseDocument(String filename) throws FileNotFoundException, IOException, Exception {
        try {
            MyDoc myDoc = new MyDoc(filename);
            File arq = new File(filename);
            FileReader fr = new FileReader(arq);
            BufferedReader br = new BufferedReader(fr);
            String linha;
            while (br.ready()) {
                /*
                 * Faz o processamento de todas as linhas do Arquivo
                 */
                linha = br.readLine();
                if (linha.contains("<Fix")) {
                    myDoc.addFix(parseFix(linha));
                } else if (linha.contains("<Key Time")) {
                    myDoc.addKey(parseKey(linha));
                } else if (linha.contains("<System") && linha.contains("STOP")) {
                    myDoc.tempoFinal = parseTempoFinal(linha);
                }
            }

            return myDoc;

        } catch (FileNotFoundException ex) {
            throw new FileNotFoundException("Arquivo " + filename + " não foi encontrado ou não pode ser lido.");
        } catch (IOException ex) {
            throw new IOException("Problema de I/O");
        } catch (Exception ex) {
            throw new Exception("Erro no parse do documento XML");
        }
    }
    
    /*
        Faz o parse das Fixações (Fix)
    */

    private static Integer parseFix(String st) throws Exception {
        org.w3c.dom.Document xmlDocument = loadXMLFromString(st);

        XPath xPath;
        xPath = XPathFactory.newInstance().newXPath();

        Node node = (Node) xPath.compile(expressionFix).evaluate(xmlDocument, XPathConstants.NODE);

        return Integer.parseInt(node.getAttributes().getNamedItem("Time").getNodeValue());
    }
    
    /*
        Faz o parse do uso de teclas (Key)
    */

    private static Key parseKey(String st) throws Exception {
        org.w3c.dom.Document xmlDocument = loadXMLFromString(st);
        XPath xPath;
        xPath = XPathFactory.newInstance().newXPath();
        Node node = (Node) xPath.compile(expressionKey).evaluate(xmlDocument, XPathConstants.NODE);

        Integer time = Integer.parseInt(node.getAttributes().getNamedItem("Time").getNodeValue());
        String value = node.getAttributes().getNamedItem("Value").getNodeValue();
        return new Key(time, value);
    }
    
    /*
        Recupera o tempo final
    */

    private static Integer parseTempoFinal(String st) throws Exception {
        org.w3c.dom.Document xmlDocument = loadXMLFromString(st);
        XPath xPath = XPathFactory.newInstance().newXPath();

        NodeList nodeList = (NodeList) xPath.compile(expressionTempoFinal).evaluate(xmlDocument, XPathConstants.NODESET);
        Integer retorno = Integer.parseInt(nodeList.item(0).getAttributes().getNamedItem("Time").getNodeValue());
        return retorno;
    }

    /*
     Cria um Documento a partir de uma String, para manipulação posterior com XPath
     Fonte: http://stackoverflow.com/questions/562160/in-java-how-do-i-parse-xml-as-a-string-instead-of-a-file
     */
    private static Document loadXMLFromString(String xml) throws Exception {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        DocumentBuilder builder = factory.newDocumentBuilder();
        InputSource is = new InputSource(new StringReader(xml));
        return builder.parse(is);
    }
}
