/**
 * MicroUnits - Pauses Analysis of XML files generated by Translog II software.
 * For Translog II details See <http://bridge.cbs.dk/platform/?q=Translog-II>
 *
 * Copyright (C) 2014 Gabriel Ed. da Silva
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package JavaFx;

import Modelo.MyPdfDocument;
import java.io.File;
import java.net.URL;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.ChoiceBox;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.stage.DirectoryChooser;
import javafx.stage.Stage;
import org.controlsfx.dialog.Dialog;

/**
 *
 * @author Gabriel Ed
 */
public class InterfaceGraficaController implements Initializable {

    @FXML
    private TextField pausas;
    @FXML
    private TextField arq;
    @FXML
    private TextField dir;
    @FXML
    private ChoiceBox<String> choice;

    @FXML
    private void dChooser(ActionEvent event) {
        DirectoryChooser dc = new DirectoryChooser();
        dc.setTitle("Escolha o diretório a ser processado");
        File file = dc.showDialog(new Stage());
        dir.setText(file.toString());
        arq.setText(file.toString() + getSlash());
    }

    @FXML
    private void doAction(MouseEvent event) {
        if (dir.getText().length() > 1) {

            try {
                MyPdfDocument.create(dir.getText(), validaNomeArquivo(arq.getText()), validaPausa(pausas.getText()), validaTipo(choice.getValue()));
            } catch (Exception ex) {
                Dialog dialog;
                dialog = new Dialog(MicroUnitsApp.stage, "Erro", true);
                dialog.setContent(ex.getMessage());
                dialog.show();
                Logger.getLogger(InterfaceGraficaController.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        System.out.println("Operação Finalizada");
        limparCampos();
    }

    private void limparCampos() {
        dir.setText("");
        pausas.setText("");
        arq.setText("");
    }

    private Integer validaPausa(String st) {
        if (st.matches("[0-9]*")) {
            return Integer.parseInt(st);
        } else {
            return 2400;
        }
    }

    private Integer validaTipo(String st) {
        if (st.equalsIgnoreCase("Fix")) {
            return 2;
        } else {
            return 1;
        }
    }

    private String validaNomeArquivo(String st) {
        if (st == null) {
            return "MicroUnits.pdf";
        } else if (st.isEmpty()) {
            return "MicroUnits.pdf";
        } else if (st.endsWith(".pdf")) {
            return st;
        } else if (st.contains(".")) {
            String[] stList = st.split(".");
            return stList[0] + ".pdf";
        } else {
            return st + ".pdf";
        }

    }

    /*
     Verifica a versão do Sistema, para retornar a barra correta para o
     caminho de um arquivo.
     */
    private String getSlash() {
        if (System.getProperty("os.name").startsWith("Windows")) {
            return "\\";
        }

        return "/";
    }

    @Override
    public void initialize(URL url, ResourceBundle rb) {
        choice.setItems(FXCollections.observableArrayList("Basico","Fix"));
    }

}
