/**
 * MicroUnits - Pauses Analysis of XML files generated by Translog II software.
 * For Translog II details See <http://bridge.cbs.dk/platform/?q=Translog-II>
 *
 * Copyright (C) 2014 Gabriel Ed. da Silva
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package Model;

/**
 * @author Gabriel Ed
 */
public class Key {

    private Integer time;
    private String value;

    /**
     * Class constructor
     * Construtor de Classe
     *
     * @param time  Time field
     * @param value  Value field
     */
    public Key(Integer time, String value) {
        this.time = time;

        /**
         * Little Trick to replace any white spaces values
         * Pequeno truque para substituir todos os espaços em branco
         */
        this.value = StringTreatment.replaceWhiteSpaces(value);
    }

    /**
     * Gets the time field
     * Recupera o campo tempo
     *
     * @return the time
     */
    public Integer getTime() {
        return time;
    }

    /**
     * Sets the time field
     * Atualiza o campo tempo
     *
     * @param time the time to set
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * Gets the value field
     * Recupera o campo valor
     *
     * @return the value
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value field
     * Atualiza o campo valor
     *
     * @param value the value to set
     */
    public void setValue(String value) {
        this.value = StringTreatment.replaceWhiteSpaces(value);
    }

}
